BerrasBio1.0/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BerrasBio1._0.Data;
using BerrasBio1._0.Models;
using System.Collections;

namespace BerrasBio1._0.Controllers
{
    public class MoviesController : Controller
    {
        private readonly CinemaContext _context;

        public MoviesController(CinemaContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Movies.Include(m=>m.Genres).ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //include all relationals
            var movie = await _context.Movies
                .Include(m=>m.Genres)
                .Include(m=>m.Actors)
                .Include(m=>m.Director)
                .Include(m=>m.Producer)
                .Include(m=>m.Showings)
                .FirstOrDefaultAsync(m => m.Id == id);
            //Reformat the trailer-url to be a youtube-embeddable url.
            string trailerUrl = movie.TrailerUrl;
            string[] splittedUrl = trailerUrl.Split('/');
            string embedUrl = $"https://www.youtube.com/embed/{splittedUrl.Last()}";
            movie.TrailerUrl = embedUrl;

            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }   
    }
}

BerrasBio1.0/Controllers/ShowingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BerrasBio1._0.Data;
using BerrasBio1._0.Models;
using BerrasBio1._0.Models.ViewModels;

namespace BerrasBio1._0.Controllers
{
    public class ShowingsController : Controller
    {
        private readonly CinemaContext _context;

        public ShowingsController(CinemaContext context)
        {
            _context = context;
        }

        // GET: Showings
        public IActionResult Index(string sortOrder)
        {
            //Sortingorders depending on what string gets sent to the action
            ViewBag.StartTime = String.IsNullOrEmpty(sortOrder) ? "StartTime" : "";
            ViewBag.StartTime = sortOrder == "StartTime" ? "start_time_desc" : "StartTime";
            ViewBag.EndTime = sortOrder == "EndTime" ? "end_time_desc" : "EndTime";
            ViewBag.MovieTitle = sortOrder == "MovieTitle" ? "movie_title_desc" : "MovieTitle";
            ViewBag.Auditorium = sortOrder == "Auditorium" ? "auditorium_desc" : "Auditorium";
            ViewBag.Seats = sortOrder == "Seats" ? "seats_desc" : "Seats"; 

            var cinemaContext = _context.Showings.Include(s => s.Auditorium).Include(s => s.Movie).Include(s => s.Seats).ToList();

            //Order the context/showinglist according to sortOrder
            switch (sortOrder)
            {
                case "StartTime":
                    cinemaContext = cinemaContext.OrderBy(s=>s.StartTime).ToList();
                    break;
                case "start_time_desc":
                    cinemaContext = cinemaContext.OrderByDescending(s => s.StartTime).ToList();
                    break;
                case "EndTime":
                    cinemaContext = cinemaContext.OrderBy(s => s.EndTime).ToList();
                    break;
                case "end_time_desc":
                    cinemaContext = cinemaContext.OrderByDescending(s => s.EndTime).ToList();
                    break;
                case "MovieTitle":
                    cinemaContext = cinemaContext.OrderBy(s => s.Movie.Name).ToList();
                    break;
                case "movie_title_desc":
                    cinemaContext = cinemaContext.OrderByDescending(s => s.Movie.Name).ToList();
                    break;
                case "Auditorium":
                    cinemaContext = cinemaContext.OrderBy(s => s.Auditorium.Name).ToList();
                    break;
                case "auditorium_desc":
                    cinemaContext = cinemaContext.OrderByDescending(s => s.Auditorium.Name).ToList();
                    break;
                case "Seats":
                    cinemaContext = cinemaContext.OrderBy(s => s.Seats.Where(s => s.Booked == false).Count()).ToList();
                    break;
                case "seats_desc":
                    cinemaContext = cinemaContext.OrderByDescending(s => s.Seats.Where(s => s.Booked == false).Count()).ToList();
                    break;
            }
            return View(cinemaContext);
        }

        // GET: Showings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //get the showing
            var showing = await _context.Showings
                .Include(s => s.Auditorium)
                .Include(s => s.Movie)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (showing == null)
            {
                return NotFound();
            }

            return View(showing);
        }
        //Get showings for a particular movie based on the ID
        public IActionResult Movie(int? id, string sortOrder)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.StartTime = String.IsNullOrEmpty(sortOrder) ? "StartTime" : "";
            ViewBag.StartTime = sortOrder == "StartTime" ? "start_time_desc" : "StartTime";
            ViewBag.EndTime = sortOrder == "EndTime" ? "end_time_desc" : "EndTime";
            ViewBag.MovieTitle = sortOrder == "MovieTitle" ? "movie_title_desc" : "MovieTitle";
            ViewBag.Auditorium = sortOrder == "Auditorium" ? "auditorium_desc" : "Auditorium";
            ViewBag.Seats = sortOrder == "Seats" ? "seats_desc" : "Seats";

            //Get showing where showing.movieID equals the id that is sent to the action
            var showings = _context.Showings
                .Where(s => s.MovieId == id)
                .Include(s => s.Auditorium)
                .Include(s => s.Movie)
                .Include(s => s.Seats).ToList();

            if (showings == null)
            {
                return NotFound();
            }

            //sort the showings
            switch (sortOrder)
            {
                case "StartTime":
                    showings = showings.OrderBy(s => s.StartTime).ToList();
                    break;
                case "start_time_desc":
                    showings = showings.OrderByDescending(s => s.StartTime).ToList();
                    break;
                case "EndTime":
                    showings = showings.OrderBy(s => s.EndTime).ToList();
                    break;
                case "end_time_desc":
                    showings = showings.OrderByDescending(s => s.EndTime).ToList();
                    break;
                case "MovieTitle":
                    showings = showings.OrderBy(s => s.Movie.Name).ToList();
                    break;
                case "movie_title_desc":
                    showings = showings.OrderByDescending(s => s.Movie.Name).ToList();
                    break;
                case "Auditorium":
                    showings = showings.OrderBy(s => s.Auditorium.Name).ToList();
                    break;
                case "auditorium_desc":
                    showings = showings.OrderByDescending(s => s.Auditorium.Name).ToList();
                    break;
                case "Seats":
                    showings = showings.OrderBy(s => s.Seats.Where(s => s.Booked == false).Count()).ToList();
                    break;
                case "seats_desc":
                    showings = showings.OrderByDescending(s => s.Seats.Where(s => s.Booked == false).Count()).ToList();
                    break;
            }
            return View(showings);
        }

        //Get the showings for TODAY - DATETIME.NOW
        public IActionResult Today(string sortOrder)
        {
            ViewBag.StartTime = String.IsNullOrEmpty(sortOrder) ? "StartTime" : "";
            ViewBag.StartTime = sortOrder == "StartTime" ? "start_time_desc" : "StartTime";
            ViewBag.EndTime = sortOrder == "EndTime" ? "end_time_desc" : "EndTime";
            ViewBag.MovieTitle = sortOrder == "MovieTitle" ? "movie_title_desc" : "MovieTitle";
            ViewBag.Auditorium = sortOrder == "Auditorium" ? "auditorium_desc" : "Auditorium";
            ViewBag.Seats = sortOrder == "Seats" ? "seats_desc" : "Seats";
            DateTime dateToday = DateTime.Today;

            var showings = _context.Showings
                .Where(s => s.StartTime.Date == dateToday.Date)
                .Include(s => s.Auditorium)
                .Include(s => s.Movie)
                .Include(s => s.Seats).ToList();

            if (showings == null)
            {
                return NotFound();
            }
            switch (sortOrder)
            {
                case "StartTime":
                    showings = showings.OrderBy(s => s.StartTime).ToList();
                    break;
                case "start_time_desc":
                    showings = showings.OrderByDescending(s => s.StartTime).ToList();
                    break;
                case "EndTime":
                    showings = showings.OrderBy(s => s.EndTime).ToList();
                    break;
                case "end_time_desc":
                    showings = showings.OrderByDescending(s => s.EndTime).ToList();
                    break;
                case "MovieTitle":
                    showings = showings.OrderBy(s => s.Movie.Name).ToList();
                    break;
                case "movie_title_desc":
                    showings = showings.OrderByDescending(s => s.Movie.Name).ToList();
                    break;
                case "Auditorium":
                    showings = showings.OrderBy(s => s.Auditorium.Name).ToList();
                    break;
                case "auditorium_desc":
                    showings = showings.OrderByDescending(s => s.Auditorium.Name).ToList();
                    break;
                case "Seats":
                    showings = showings.OrderBy(s => s.Seats.Where(s => s.Booked == false).Count()).ToList();
                    break;
                case "seats_desc":
                    showings = showings.OrderByDescending(s => s.Seats.Where(s => s.Booked == false).Count()).ToList();
                    break;
            }
            return View(showings);
        }

        //Create/edit/delete showing (Would be protected in a real world project)
        // GET: Showings/Create
        public IActionResult Create()
        {
            ViewData["AuditoriumId"] = new SelectList(_context.Auditoriums, "Id", "Name");
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Name");
            return View();
        }

        // POST: Showings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StartTime,MovieId,AuditoriumId,Price")] Showing showing)
        {
            if (ModelState.IsValid)

BerrasBio1.0/Views/Movies/Details.cshtml
@model BerrasBio1._0.Models.Movie
@{
  ViewData["Title"] = "Details";
}

@*Show details about a selected movie*@
<div class="movie-details">

  <div class="flex-column">
    <div class="movie-details-nav">
      <ul class="movie-details-nav-list" id="movie-details-nav-list">
        <li class="movie-details-nav-item active" data-link="about"><span>About</span></li>
        <li class="movie-details-nav-item" data-link="trailer"><span>Trailer</span></li>
      </ul>
    </div>
    <div class="movie-details-inner" id="movie-details-inner-about">
      <div class="movie-details-poster-container">
        <img src="~/assets/img/posters/@Model.ImageUrl" class="movie-details-poster-img" />
      </div>
      <div class="movie-details-info">
        <h1>@Html.DisplayFor(model => model.Name)</h1>
        @foreach (var genre in Model.Genres)
        {
          <span class="movie-detail-info-genre">@genre.Name</span>
        }
        <div class="movie-detail-info-plot">
          <h4>Plot</h4>
          <p>@Model.Plot</p>
        </div>
        <div class="movie-detail-info-crew">
          <div class="flex">
            <div>
              @if (@Model.Director != null)
              {
                <h4>Director</h4>
                @Model.Director.Name
              }

            </div>
            <div class="ml-20">
              @if (@Model.Producer != null)
              {
                <h4>Producer</h4>
                @Model.Producer.Name
              }
            </div>
          </div>
          @if (@Model.Actors.Count > 3)
          {
            <h4 class="mt-20">Featuring</h4>
            @for (int i = 0; i < 3; i++)
            {
              <p>@Model.Actors.ToList()[i].Name</p>
            }
          }
        </div>
        <div class="movie-detail-btn-container mt-20">
          <a asp-controller="Showings" asp-action="Movie" asp-route-id="@Model.Id" class="btn-primary">Book tickets</a>
        </div>
      </div>
    </div>

      <div class="movie-details-inner  display-none" id="movie-details-inner-trailer">
        <iframe width="640" height="480" src="@Model.TrailerUrl" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
  </div>
<div class="movie-details-bg-container"><img src="~/assets/img/backdrops/@Model.BackdropUrl" class="movie-details-bg" /></div>


<script>
  //Javascript to handle the navigationbar to switch between trailer and info tab
  let movieDetailsNav = document.getElementById("movie-details-nav-list");
  let aboutSection = document.getElementById("movie-details-inner-about");
  let trailerSection = document.getElementById("movie-details-inner-trailer");

  movieDetailsNav.addEventListener('click', function (event) {
  if (event.target.parentElement.getAttribute("data-link") != null) {
    let links = document.getElementById("movie-details-nav-list").getElementsByTagName("li");
    for (let i = 0; i < links.length; i++) {
      links[i].classList.remove("active")
    }
    let link = event.target.parentElement.getAttribute("data-link");
    switch (link) {
      case "about":
        event.target.parentElement.classList.add("active");
        trailerSection.classList.add("display-none")
        aboutSection.classList.remove("display-none")
        console.log("About click");
        break;
      case "trailer":
        event.target.parentElement.classList.add("active");
        aboutSection.classList.add("display-none")
        trailerSection.classList.remove("display-none")
        console.log("Trailer click");
        break;
    }
  }
}, false);
</script>

BerrasBio1.0/Views/Movies/Index.cshtml
@model IEnumerable<BerrasBio1._0.Models.Movie>

@{
  ViewData["Title"] = "Index";
}

@*The main moviepage, with one large carousel to showcase 6 movies*@
<div class="movie-index">
  <div class="main-carousel">
    @foreach (var item in Model.Take(6))
    {
    <div class="main-carousel-item">
      <img src="~/assets/img/backdrops/@item.BackdropUrl" class="main-carousel-item-bg" />
      <a asp-controller="Movies" asp-action="details" asp-route-id="@item.Id" class="btn-primary" id="main-carousel-btn">More info</a>
        <h1 class="main-carousel-title">@item.Name</h1>
    </div>
    }
  </div>
  @*And then a couple of smaller carousels based on their genre*@
  <div class="sub-carousels-container">
    <h2 class="sub-carousel-heading">Crime</h2>
    <div class="sub-carousel">
      @foreach (var item in Model.Where(m => m.Genres.Any(g => g.Name == "Crime")).ToList())
      {
        <div class="sub-carousel-item">
          <a asp-controller="Movies" asp-action="details" asp-route-id="@item.Id">
            <img src="~/assets/img/posters/@item.ImageUrl" class="sub-carousel-item-img" />
          </a>
        </div>
      }
    </div>
    <h2 class="sub-carousel-heading">Family</h2>
    <div class="sub-carousel">
      @foreach (var item in Model.Where(m => m.Genres.Any(g => g.Name == "Family")).ToList())
      {
        <div class="sub-carousel-item">
          <a asp-controller="Movies" asp-action="details" asp-route-id="@item.Id">
            <img src="~/assets/img/posters/@item.ImageUrl" class="sub-carousel-item-img" />
          </a>
        </div>
      }
    </div>
    <h2 class="sub-carousel-heading">Comedy</h2>
    <div class="sub-carousel">
      @foreach (var item in Model.Where(m => m.Genres.Any(g => g.Name == "Comedy")).ToList())
      {
        <div class="sub-carousel-item">
          <a asp-controller="Movies" asp-action="details" asp-route-id="@item.Id">
            <img src="~/assets/img/posters/@item.ImageUrl" class="sub-carousel-item-img" />
          </a>
        </div>
      }
    </div>
    <h2 class="sub-carousel-heading">Adventure</h2>
    <div class="sub-carousel">
      @foreach (var item in Model.Where(m => m.Genres.Any(g => g.Name == "Adventure")).ToList())
      {
        <div class="sub-carousel-item">
          <a asp-controller="Movies" asp-action="details" asp-route-id="@item.Id">
            <img src="~/assets/img/posters/@item.ImageUrl" class="sub-carousel-item-img" />
          </a>
        </div>
      }
    </div>
    <h2 class="sub-carousel-heading">Drama</h2>
    <div class="sub-carousel">
      @foreach (var item in Model.Where(m => m.Genres.Any(g => g.Name == "Drama")).ToList())
      {
        <div class="sub-carousel-item">
          <a asp-controller="Movies" asp-action="details" asp-route-id="@item.Id">
            <img src="~/assets/img/posters/@item.ImageUrl" class="sub-carousel-item-img" />
          </a>
        </div>
      }
    </div>

  </div>

  </div>